spring:
  application:
    name: springdatajdbc
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/core?currentSchema=core&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
      username: postgres
      password: postgres

logging:
  level:
    org:
      springframework:
        jdbc: debug
    sql: debug
